import re
str1=input()
str2=input()
str2=list(str2)
str2.insert(0,'[')
str2.append(']')
str2=''.join(str2)
a=re.compile(str2)
print(re.compile(str2))
mo=a.findall(str1)
print("".join(mo))
print(''.join(re.findall(str2,str1)))